<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>promise error handling</title>
    </head>
    <body>
        <h1>promise error handling</h1>
    </body>
        <script>
            // promise는 예외 발생 시 암시적 try..catch에서 예외 잡고 이를 reject처럼 다룸
            // 아래의 두 예제는 동일하게 동작함
            new Promise((resolve, reject) => {
                throw new Error('error! 1');
            }).catch(alert); // Error: error!

            new Promise((resolve, reject) => {
                reject(new Error('error! 2'));
            }).catch(alert); // Error: error!

            // .then 핸들러 안에서 throw를 사용해 에러를 던지면
            // 이 자체가 거부된 프라미스를 의미하게 됨
            // 따라서 제어 흐름이 가장 가까운 에러 핸들러로 넘어감
            new Promise((resolve, reject) => {
                resolve('OK');
            }).then(result => {
                throw new Error('error! 3'); // promise 거부됨
            }).catch(alert); // Error: error!

            // 핸들러 위족에서 발생한 에러 잡기
            new Promise((resolve, reject) => {
                resolve("OK");
            }).then((result) => {
                blabla(); // 존재하지 않는 함수
            }).catch(alert); // ReferenceError: blabla is not defined

            // 에러 다시 던지기
            // 실행 순서: catch -> catch
            new Promise((resolve, reject) => {

                throw new Error("에러 발생!");

            }).catch(function(error) { // (*) 여기로 넘어갔다가

                if (error instanceof URIError) {
                    // 에러 처리
                } else {
                    alert("처리할 수 없는 에러");

                    throw error; // 에러 다시 던지기
                }

            }).then(function() {
                /* 여기는 실행되지 않습니다. */
            }).catch(error => { // (**) 여기로 이어짐

                alert(`알 수 없는 에러가 발생함: ${error}`);
                // 반환값이 없음 => 실행이 계속됨

            });

            // 예외를 처리해줄 핸들러가 없어서 에러가 갖혀버리는 경우
            // 자바스크립트 엔진이 전역 에러 생성
            new Promise(function() {
                noSuchFunction(); // 존재하지 않는 함수를 호출하기 때문에 에러가 발생함
            })
            .then(() => {
                // 성공상태의 프라미스를 처리하는 핸들러. 한 개 혹은 여러 개가 있을 수 있음
            }); // 끝에 .catch가 없음!

         </script>
</html>